[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
